// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"transcoder/server/internal/models"
)

func newFile(db *gorm.DB, opts ...gen.DOOption) file {
	_file := file{}

	_file.fileDo.UseDB(db, opts...)
	_file.fileDo.UseModel(&models.File{})

	tableName := _file.fileDo.TableName()
	_file.ALL = field.NewAsterisk(tableName)
	_file.ID = field.NewField(tableName, "id")
	_file.CreatedAt = field.NewTime(tableName, "created_at")
	_file.UpdatedAt = field.NewTime(tableName, "updated_at")
	_file.Name = field.NewString(tableName, "name")
	_file.Path = field.NewString(tableName, "path")
	_file.Size = field.NewInt64(tableName, "size")
	_file.MimeType = field.NewString(tableName, "mime_type")
	_file.OwnerID = field.NewField(tableName, "owner_id")
	_file.InputToJobs = fileHasManyInputToJobs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("InputToJobs", "models.Job"),
		Owner: struct {
			field.RelationField
			Jobs struct {
				field.RelationField
			}
			Tasks struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}
			Workflows struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("InputToJobs.Owner", "models.User"),
			Jobs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("InputToJobs.Owner.Jobs", "models.Job"),
			},
			Tasks: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("InputToJobs.Owner.Tasks", "models.Task"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("InputToJobs.Owner.Tasks.Owner", "models.User"),
				},
				Workflow: struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("InputToJobs.Owner.Tasks.Workflow", "models.Workflow"),
					Owner: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("InputToJobs.Owner.Tasks.Workflow.Owner", "models.User"),
					},
					Jobs: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("InputToJobs.Owner.Tasks.Workflow.Jobs", "models.Job"),
					},
					Tasks: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("InputToJobs.Owner.Tasks.Workflow.Tasks", "models.Task"),
					},
				},
				Jobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("InputToJobs.Owner.Tasks.Jobs", "models.Job"),
				},
			},
			Workflows: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("InputToJobs.Owner.Workflows", "models.Workflow"),
			},
			Files: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("InputToJobs.Owner.Files", "models.File"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("InputToJobs.Owner.Files.Owner", "models.User"),
				},
				InputToJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("InputToJobs.Owner.Files.InputToJobs", "models.Job"),
				},
				OutputFromJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("InputToJobs.Owner.Files.OutputFromJobs", "models.Job"),
				},
			},
		},
		Task: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("InputToJobs.Task", "models.Task"),
		},
		Workflow: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("InputToJobs.Workflow", "models.Workflow"),
		},
		InputFile: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("InputToJobs.InputFile", "models.File"),
		},
		OutputFile: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("InputToJobs.OutputFile", "models.File"),
		},
	}

	_file.OutputFromJobs = fileHasManyOutputFromJobs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("OutputFromJobs", "models.Job"),
	}

	_file.Owner = fileBelongsToOwner{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Owner", "models.User"),
	}

	_file.fillFieldMap()

	return _file
}

type file struct {
	fileDo

	ALL         field.Asterisk
	ID          field.Field
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Name        field.String
	Path        field.String
	Size        field.Int64
	MimeType    field.String
	OwnerID     field.Field
	InputToJobs fileHasManyInputToJobs

	OutputFromJobs fileHasManyOutputFromJobs

	Owner fileBelongsToOwner

	fieldMap map[string]field.Expr
}

func (f file) Table(newTableName string) *file {
	f.fileDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f file) As(alias string) *file {
	f.fileDo.DO = *(f.fileDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *file) updateTableName(table string) *file {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewField(table, "id")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.Name = field.NewString(table, "name")
	f.Path = field.NewString(table, "path")
	f.Size = field.NewInt64(table, "size")
	f.MimeType = field.NewString(table, "mime_type")
	f.OwnerID = field.NewField(table, "owner_id")

	f.fillFieldMap()

	return f
}

func (f *file) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *file) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 11)
	f.fieldMap["id"] = f.ID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["name"] = f.Name
	f.fieldMap["path"] = f.Path
	f.fieldMap["size"] = f.Size
	f.fieldMap["mime_type"] = f.MimeType
	f.fieldMap["owner_id"] = f.OwnerID

}

func (f file) clone(db *gorm.DB) file {
	f.fileDo.ReplaceConnPool(db.Statement.ConnPool)
	f.InputToJobs.db = db.Session(&gorm.Session{Initialized: true})
	f.InputToJobs.db.Statement.ConnPool = db.Statement.ConnPool
	f.OutputFromJobs.db = db.Session(&gorm.Session{Initialized: true})
	f.OutputFromJobs.db.Statement.ConnPool = db.Statement.ConnPool
	f.Owner.db = db.Session(&gorm.Session{Initialized: true})
	f.Owner.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f file) replaceDB(db *gorm.DB) file {
	f.fileDo.ReplaceDB(db)
	f.InputToJobs.db = db.Session(&gorm.Session{})
	f.OutputFromJobs.db = db.Session(&gorm.Session{})
	f.Owner.db = db.Session(&gorm.Session{})
	return f
}

type fileHasManyInputToJobs struct {
	db *gorm.DB

	field.RelationField

	Owner struct {
		field.RelationField
		Jobs struct {
			field.RelationField
		}
		Tasks struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Workflow struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Jobs struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
			}
			Jobs struct {
				field.RelationField
			}
		}
		Workflows struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			InputToJobs struct {
				field.RelationField
			}
			OutputFromJobs struct {
				field.RelationField
			}
		}
	}
	Task struct {
		field.RelationField
	}
	Workflow struct {
		field.RelationField
	}
	InputFile struct {
		field.RelationField
	}
	OutputFile struct {
		field.RelationField
	}
}

func (a fileHasManyInputToJobs) Where(conds ...field.Expr) *fileHasManyInputToJobs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileHasManyInputToJobs) WithContext(ctx context.Context) *fileHasManyInputToJobs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileHasManyInputToJobs) Session(session *gorm.Session) *fileHasManyInputToJobs {
	a.db = a.db.Session(session)
	return &a
}

func (a fileHasManyInputToJobs) Model(m *models.File) *fileHasManyInputToJobsTx {
	return &fileHasManyInputToJobsTx{a.db.Model(m).Association(a.Name())}
}

func (a fileHasManyInputToJobs) Unscoped() *fileHasManyInputToJobs {
	a.db = a.db.Unscoped()
	return &a
}

type fileHasManyInputToJobsTx struct{ tx *gorm.Association }

func (a fileHasManyInputToJobsTx) Find() (result []*models.Job, err error) {
	return result, a.tx.Find(&result)
}

func (a fileHasManyInputToJobsTx) Append(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileHasManyInputToJobsTx) Replace(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileHasManyInputToJobsTx) Delete(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileHasManyInputToJobsTx) Clear() error {
	return a.tx.Clear()
}

func (a fileHasManyInputToJobsTx) Count() int64 {
	return a.tx.Count()
}

func (a fileHasManyInputToJobsTx) Unscoped() *fileHasManyInputToJobsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type fileHasManyOutputFromJobs struct {
	db *gorm.DB

	field.RelationField
}

func (a fileHasManyOutputFromJobs) Where(conds ...field.Expr) *fileHasManyOutputFromJobs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileHasManyOutputFromJobs) WithContext(ctx context.Context) *fileHasManyOutputFromJobs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileHasManyOutputFromJobs) Session(session *gorm.Session) *fileHasManyOutputFromJobs {
	a.db = a.db.Session(session)
	return &a
}

func (a fileHasManyOutputFromJobs) Model(m *models.File) *fileHasManyOutputFromJobsTx {
	return &fileHasManyOutputFromJobsTx{a.db.Model(m).Association(a.Name())}
}

func (a fileHasManyOutputFromJobs) Unscoped() *fileHasManyOutputFromJobs {
	a.db = a.db.Unscoped()
	return &a
}

type fileHasManyOutputFromJobsTx struct{ tx *gorm.Association }

func (a fileHasManyOutputFromJobsTx) Find() (result []*models.Job, err error) {
	return result, a.tx.Find(&result)
}

func (a fileHasManyOutputFromJobsTx) Append(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileHasManyOutputFromJobsTx) Replace(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileHasManyOutputFromJobsTx) Delete(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileHasManyOutputFromJobsTx) Clear() error {
	return a.tx.Clear()
}

func (a fileHasManyOutputFromJobsTx) Count() int64 {
	return a.tx.Count()
}

func (a fileHasManyOutputFromJobsTx) Unscoped() *fileHasManyOutputFromJobsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type fileBelongsToOwner struct {
	db *gorm.DB

	field.RelationField
}

func (a fileBelongsToOwner) Where(conds ...field.Expr) *fileBelongsToOwner {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a fileBelongsToOwner) WithContext(ctx context.Context) *fileBelongsToOwner {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a fileBelongsToOwner) Session(session *gorm.Session) *fileBelongsToOwner {
	a.db = a.db.Session(session)
	return &a
}

func (a fileBelongsToOwner) Model(m *models.File) *fileBelongsToOwnerTx {
	return &fileBelongsToOwnerTx{a.db.Model(m).Association(a.Name())}
}

func (a fileBelongsToOwner) Unscoped() *fileBelongsToOwner {
	a.db = a.db.Unscoped()
	return &a
}

type fileBelongsToOwnerTx struct{ tx *gorm.Association }

func (a fileBelongsToOwnerTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a fileBelongsToOwnerTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a fileBelongsToOwnerTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a fileBelongsToOwnerTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a fileBelongsToOwnerTx) Clear() error {
	return a.tx.Clear()
}

func (a fileBelongsToOwnerTx) Count() int64 {
	return a.tx.Count()
}

func (a fileBelongsToOwnerTx) Unscoped() *fileBelongsToOwnerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type fileDo struct{ gen.DO }

type IFileDo interface {
	gen.SubQuery
	Debug() IFileDo
	WithContext(ctx context.Context) IFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileDo
	WriteDB() IFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileDo
	Not(conds ...gen.Condition) IFileDo
	Or(conds ...gen.Condition) IFileDo
	Select(conds ...field.Expr) IFileDo
	Where(conds ...gen.Condition) IFileDo
	Order(conds ...field.Expr) IFileDo
	Distinct(cols ...field.Expr) IFileDo
	Omit(cols ...field.Expr) IFileDo
	Join(table schema.Tabler, on ...field.Expr) IFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileDo
	Group(cols ...field.Expr) IFileDo
	Having(conds ...gen.Condition) IFileDo
	Limit(limit int) IFileDo
	Offset(offset int) IFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileDo
	Unscoped() IFileDo
	Create(values ...*models.File) error
	CreateInBatches(values []*models.File, batchSize int) error
	Save(values ...*models.File) error
	First() (*models.File, error)
	Take() (*models.File, error)
	Last() (*models.File, error)
	Find() ([]*models.File, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.File, err error)
	FindInBatches(result *[]*models.File, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.File) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileDo
	Assign(attrs ...field.AssignExpr) IFileDo
	Joins(fields ...field.RelationField) IFileDo
	Preload(fields ...field.RelationField) IFileDo
	FirstOrInit() (*models.File, error)
	FirstOrCreate() (*models.File, error)
	FindByPage(offset int, limit int) (result []*models.File, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileDo) Debug() IFileDo {
	return f.withDO(f.DO.Debug())
}

func (f fileDo) WithContext(ctx context.Context) IFileDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileDo) ReadDB() IFileDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileDo) WriteDB() IFileDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileDo) Session(config *gorm.Session) IFileDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileDo) Clauses(conds ...clause.Expression) IFileDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileDo) Returning(value interface{}, columns ...string) IFileDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileDo) Not(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileDo) Or(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileDo) Select(conds ...field.Expr) IFileDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileDo) Where(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileDo) Order(conds ...field.Expr) IFileDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileDo) Distinct(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileDo) Omit(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileDo) Join(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileDo) Group(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileDo) Having(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileDo) Limit(limit int) IFileDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileDo) Offset(offset int) IFileDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileDo) Unscoped() IFileDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileDo) Create(values ...*models.File) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileDo) CreateInBatches(values []*models.File, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileDo) Save(values ...*models.File) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileDo) First() (*models.File, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) Take() (*models.File, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) Last() (*models.File, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) Find() ([]*models.File, error) {
	result, err := f.DO.Find()
	return result.([]*models.File), err
}

func (f fileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.File, err error) {
	buf := make([]*models.File, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileDo) FindInBatches(result *[]*models.File, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileDo) Attrs(attrs ...field.AssignExpr) IFileDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileDo) Assign(attrs ...field.AssignExpr) IFileDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileDo) Joins(fields ...field.RelationField) IFileDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileDo) Preload(fields ...field.RelationField) IFileDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileDo) FirstOrInit() (*models.File, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) FirstOrCreate() (*models.File, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.File), nil
	}
}

func (f fileDo) FindByPage(offset int, limit int) (result []*models.File, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileDo) Delete(models ...*models.File) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileDo) withDO(do gen.Dao) *fileDo {
	f.DO = *do.(*gen.DO)
	return f
}
