// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q        = new(Query)
	File     *file
	Job      *job
	Task     *task
	User     *user
	Workflow *workflow
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	File = &Q.File
	Job = &Q.Job
	Task = &Q.Task
	User = &Q.User
	Workflow = &Q.Workflow
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:       db,
		File:     newFile(db, opts...),
		Job:      newJob(db, opts...),
		Task:     newTask(db, opts...),
		User:     newUser(db, opts...),
		Workflow: newWorkflow(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	File     file
	Job      job
	Task     task
	User     user
	Workflow workflow
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:       db,
		File:     q.File.clone(db),
		Job:      q.Job.clone(db),
		Task:     q.Task.clone(db),
		User:     q.User.clone(db),
		Workflow: q.Workflow.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:       db,
		File:     q.File.replaceDB(db),
		Job:      q.Job.replaceDB(db),
		Task:     q.Task.replaceDB(db),
		User:     q.User.replaceDB(db),
		Workflow: q.Workflow.replaceDB(db),
	}
}

type queryCtx struct {
	File     IFileDo
	Job      IJobDo
	Task     ITaskDo
	User     IUserDo
	Workflow IWorkflowDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		File:     q.File.WithContext(ctx),
		Job:      q.Job.WithContext(ctx),
		Task:     q.Task.WithContext(ctx),
		User:     q.User.WithContext(ctx),
		Workflow: q.Workflow.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
