// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"transcoder/server/internal/models"
)

func newJob(db *gorm.DB, opts ...gen.DOOption) job {
	_job := job{}

	_job.jobDo.UseDB(db, opts...)
	_job.jobDo.UseModel(&models.Job{})

	tableName := _job.jobDo.TableName()
	_job.ALL = field.NewAsterisk(tableName)
	_job.ID = field.NewField(tableName, "id")
	_job.CreatedAt = field.NewTime(tableName, "created_at")
	_job.UpdatedAt = field.NewTime(tableName, "updated_at")
	_job.Status = field.NewString(tableName, "status")
	_job.InputPath = field.NewString(tableName, "input_path")
	_job.OutputPath = field.NewString(tableName, "output_path")
	_job.TargetFormat = field.NewString(tableName, "target_format")
	_job.Params = field.NewString(tableName, "params")
	_job.Progress = field.NewInt(tableName, "progress")
	_job.ErrorMessage = field.NewString(tableName, "error_message")
	_job.OwnerID = field.NewField(tableName, "owner_id")
	_job.TaskID = field.NewField(tableName, "task_id")
	_job.WorkflowID = field.NewField(tableName, "workflow_id")
	_job.InputFileID = field.NewField(tableName, "input_file_id")
	_job.OutputFileID = field.NewField(tableName, "output_file_id")
	_job.Owner = jobBelongsToOwner{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Owner", "models.User"),
		Jobs: struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Task struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}
			Workflow struct {
				field.RelationField
			}
			InputFile struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}
			OutputFile struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Owner.Jobs", "models.Job"),
			Owner: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Owner.Jobs.Owner", "models.User"),
			},
			Task: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Owner.Jobs.Task", "models.Task"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Owner.Jobs.Task.Owner", "models.User"),
				},
				Workflow: struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Owner.Jobs.Task.Workflow", "models.Workflow"),
					Owner: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Owner.Jobs.Task.Workflow.Owner", "models.User"),
					},
					Jobs: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Owner.Jobs.Task.Workflow.Jobs", "models.Job"),
					},
					Tasks: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Owner.Jobs.Task.Workflow.Tasks", "models.Task"),
					},
				},
				Jobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Owner.Jobs.Task.Jobs", "models.Job"),
				},
			},
			Workflow: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Owner.Jobs.Workflow", "models.Workflow"),
			},
			InputFile: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Owner.Jobs.InputFile", "models.File"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Owner.Jobs.InputFile.Owner", "models.User"),
				},
				InputToJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Owner.Jobs.InputFile.InputToJobs", "models.Job"),
				},
				OutputFromJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Owner.Jobs.InputFile.OutputFromJobs", "models.Job"),
				},
			},
			OutputFile: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Owner.Jobs.OutputFile", "models.File"),
			},
		},
		Tasks: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Owner.Tasks", "models.Task"),
		},
		Workflows: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Owner.Workflows", "models.Workflow"),
		},
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Owner.Files", "models.File"),
		},
	}

	_job.Task = jobBelongsToTask{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Task", "models.Task"),
	}

	_job.Workflow = jobBelongsToWorkflow{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Workflow", "models.Workflow"),
	}

	_job.InputFile = jobBelongsToInputFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("InputFile", "models.File"),
	}

	_job.OutputFile = jobBelongsToOutputFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("OutputFile", "models.File"),
	}

	_job.fillFieldMap()

	return _job
}

type job struct {
	jobDo

	ALL          field.Asterisk
	ID           field.Field
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Status       field.String
	InputPath    field.String
	OutputPath   field.String
	TargetFormat field.String
	Params       field.String
	Progress     field.Int
	ErrorMessage field.String
	OwnerID      field.Field
	TaskID       field.Field
	WorkflowID   field.Field
	InputFileID  field.Field
	OutputFileID field.Field
	Owner        jobBelongsToOwner

	Task jobBelongsToTask

	Workflow jobBelongsToWorkflow

	InputFile jobBelongsToInputFile

	OutputFile jobBelongsToOutputFile

	fieldMap map[string]field.Expr
}

func (j job) Table(newTableName string) *job {
	j.jobDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j job) As(alias string) *job {
	j.jobDo.DO = *(j.jobDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *job) updateTableName(table string) *job {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewField(table, "id")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.Status = field.NewString(table, "status")
	j.InputPath = field.NewString(table, "input_path")
	j.OutputPath = field.NewString(table, "output_path")
	j.TargetFormat = field.NewString(table, "target_format")
	j.Params = field.NewString(table, "params")
	j.Progress = field.NewInt(table, "progress")
	j.ErrorMessage = field.NewString(table, "error_message")
	j.OwnerID = field.NewField(table, "owner_id")
	j.TaskID = field.NewField(table, "task_id")
	j.WorkflowID = field.NewField(table, "workflow_id")
	j.InputFileID = field.NewField(table, "input_file_id")
	j.OutputFileID = field.NewField(table, "output_file_id")

	j.fillFieldMap()

	return j
}

func (j *job) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *job) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 20)
	j.fieldMap["id"] = j.ID
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["status"] = j.Status
	j.fieldMap["input_path"] = j.InputPath
	j.fieldMap["output_path"] = j.OutputPath
	j.fieldMap["target_format"] = j.TargetFormat
	j.fieldMap["params"] = j.Params
	j.fieldMap["progress"] = j.Progress
	j.fieldMap["error_message"] = j.ErrorMessage
	j.fieldMap["owner_id"] = j.OwnerID
	j.fieldMap["task_id"] = j.TaskID
	j.fieldMap["workflow_id"] = j.WorkflowID
	j.fieldMap["input_file_id"] = j.InputFileID
	j.fieldMap["output_file_id"] = j.OutputFileID

}

func (j job) clone(db *gorm.DB) job {
	j.jobDo.ReplaceConnPool(db.Statement.ConnPool)
	j.Owner.db = db.Session(&gorm.Session{Initialized: true})
	j.Owner.db.Statement.ConnPool = db.Statement.ConnPool
	j.Task.db = db.Session(&gorm.Session{Initialized: true})
	j.Task.db.Statement.ConnPool = db.Statement.ConnPool
	j.Workflow.db = db.Session(&gorm.Session{Initialized: true})
	j.Workflow.db.Statement.ConnPool = db.Statement.ConnPool
	j.InputFile.db = db.Session(&gorm.Session{Initialized: true})
	j.InputFile.db.Statement.ConnPool = db.Statement.ConnPool
	j.OutputFile.db = db.Session(&gorm.Session{Initialized: true})
	j.OutputFile.db.Statement.ConnPool = db.Statement.ConnPool
	return j
}

func (j job) replaceDB(db *gorm.DB) job {
	j.jobDo.ReplaceDB(db)
	j.Owner.db = db.Session(&gorm.Session{})
	j.Task.db = db.Session(&gorm.Session{})
	j.Workflow.db = db.Session(&gorm.Session{})
	j.InputFile.db = db.Session(&gorm.Session{})
	j.OutputFile.db = db.Session(&gorm.Session{})
	return j
}

type jobBelongsToOwner struct {
	db *gorm.DB

	field.RelationField

	Jobs struct {
		field.RelationField
		Owner struct {
			field.RelationField
		}
		Task struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Workflow struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Jobs struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
			}
			Jobs struct {
				field.RelationField
			}
		}
		Workflow struct {
			field.RelationField
		}
		InputFile struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			InputToJobs struct {
				field.RelationField
			}
			OutputFromJobs struct {
				field.RelationField
			}
		}
		OutputFile struct {
			field.RelationField
		}
	}
	Tasks struct {
		field.RelationField
	}
	Workflows struct {
		field.RelationField
	}
	Files struct {
		field.RelationField
	}
}

func (a jobBelongsToOwner) Where(conds ...field.Expr) *jobBelongsToOwner {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a jobBelongsToOwner) WithContext(ctx context.Context) *jobBelongsToOwner {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a jobBelongsToOwner) Session(session *gorm.Session) *jobBelongsToOwner {
	a.db = a.db.Session(session)
	return &a
}

func (a jobBelongsToOwner) Model(m *models.Job) *jobBelongsToOwnerTx {
	return &jobBelongsToOwnerTx{a.db.Model(m).Association(a.Name())}
}

func (a jobBelongsToOwner) Unscoped() *jobBelongsToOwner {
	a.db = a.db.Unscoped()
	return &a
}

type jobBelongsToOwnerTx struct{ tx *gorm.Association }

func (a jobBelongsToOwnerTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a jobBelongsToOwnerTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a jobBelongsToOwnerTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a jobBelongsToOwnerTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a jobBelongsToOwnerTx) Clear() error {
	return a.tx.Clear()
}

func (a jobBelongsToOwnerTx) Count() int64 {
	return a.tx.Count()
}

func (a jobBelongsToOwnerTx) Unscoped() *jobBelongsToOwnerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type jobBelongsToTask struct {
	db *gorm.DB

	field.RelationField
}

func (a jobBelongsToTask) Where(conds ...field.Expr) *jobBelongsToTask {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a jobBelongsToTask) WithContext(ctx context.Context) *jobBelongsToTask {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a jobBelongsToTask) Session(session *gorm.Session) *jobBelongsToTask {
	a.db = a.db.Session(session)
	return &a
}

func (a jobBelongsToTask) Model(m *models.Job) *jobBelongsToTaskTx {
	return &jobBelongsToTaskTx{a.db.Model(m).Association(a.Name())}
}

func (a jobBelongsToTask) Unscoped() *jobBelongsToTask {
	a.db = a.db.Unscoped()
	return &a
}

type jobBelongsToTaskTx struct{ tx *gorm.Association }

func (a jobBelongsToTaskTx) Find() (result *models.Task, err error) {
	return result, a.tx.Find(&result)
}

func (a jobBelongsToTaskTx) Append(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a jobBelongsToTaskTx) Replace(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a jobBelongsToTaskTx) Delete(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a jobBelongsToTaskTx) Clear() error {
	return a.tx.Clear()
}

func (a jobBelongsToTaskTx) Count() int64 {
	return a.tx.Count()
}

func (a jobBelongsToTaskTx) Unscoped() *jobBelongsToTaskTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type jobBelongsToWorkflow struct {
	db *gorm.DB

	field.RelationField
}

func (a jobBelongsToWorkflow) Where(conds ...field.Expr) *jobBelongsToWorkflow {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a jobBelongsToWorkflow) WithContext(ctx context.Context) *jobBelongsToWorkflow {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a jobBelongsToWorkflow) Session(session *gorm.Session) *jobBelongsToWorkflow {
	a.db = a.db.Session(session)
	return &a
}

func (a jobBelongsToWorkflow) Model(m *models.Job) *jobBelongsToWorkflowTx {
	return &jobBelongsToWorkflowTx{a.db.Model(m).Association(a.Name())}
}

func (a jobBelongsToWorkflow) Unscoped() *jobBelongsToWorkflow {
	a.db = a.db.Unscoped()
	return &a
}

type jobBelongsToWorkflowTx struct{ tx *gorm.Association }

func (a jobBelongsToWorkflowTx) Find() (result *models.Workflow, err error) {
	return result, a.tx.Find(&result)
}

func (a jobBelongsToWorkflowTx) Append(values ...*models.Workflow) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a jobBelongsToWorkflowTx) Replace(values ...*models.Workflow) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a jobBelongsToWorkflowTx) Delete(values ...*models.Workflow) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a jobBelongsToWorkflowTx) Clear() error {
	return a.tx.Clear()
}

func (a jobBelongsToWorkflowTx) Count() int64 {
	return a.tx.Count()
}

func (a jobBelongsToWorkflowTx) Unscoped() *jobBelongsToWorkflowTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type jobBelongsToInputFile struct {
	db *gorm.DB

	field.RelationField
}

func (a jobBelongsToInputFile) Where(conds ...field.Expr) *jobBelongsToInputFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a jobBelongsToInputFile) WithContext(ctx context.Context) *jobBelongsToInputFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a jobBelongsToInputFile) Session(session *gorm.Session) *jobBelongsToInputFile {
	a.db = a.db.Session(session)
	return &a
}

func (a jobBelongsToInputFile) Model(m *models.Job) *jobBelongsToInputFileTx {
	return &jobBelongsToInputFileTx{a.db.Model(m).Association(a.Name())}
}

func (a jobBelongsToInputFile) Unscoped() *jobBelongsToInputFile {
	a.db = a.db.Unscoped()
	return &a
}

type jobBelongsToInputFileTx struct{ tx *gorm.Association }

func (a jobBelongsToInputFileTx) Find() (result *models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a jobBelongsToInputFileTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a jobBelongsToInputFileTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a jobBelongsToInputFileTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a jobBelongsToInputFileTx) Clear() error {
	return a.tx.Clear()
}

func (a jobBelongsToInputFileTx) Count() int64 {
	return a.tx.Count()
}

func (a jobBelongsToInputFileTx) Unscoped() *jobBelongsToInputFileTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type jobBelongsToOutputFile struct {
	db *gorm.DB

	field.RelationField
}

func (a jobBelongsToOutputFile) Where(conds ...field.Expr) *jobBelongsToOutputFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a jobBelongsToOutputFile) WithContext(ctx context.Context) *jobBelongsToOutputFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a jobBelongsToOutputFile) Session(session *gorm.Session) *jobBelongsToOutputFile {
	a.db = a.db.Session(session)
	return &a
}

func (a jobBelongsToOutputFile) Model(m *models.Job) *jobBelongsToOutputFileTx {
	return &jobBelongsToOutputFileTx{a.db.Model(m).Association(a.Name())}
}

func (a jobBelongsToOutputFile) Unscoped() *jobBelongsToOutputFile {
	a.db = a.db.Unscoped()
	return &a
}

type jobBelongsToOutputFileTx struct{ tx *gorm.Association }

func (a jobBelongsToOutputFileTx) Find() (result *models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a jobBelongsToOutputFileTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a jobBelongsToOutputFileTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a jobBelongsToOutputFileTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a jobBelongsToOutputFileTx) Clear() error {
	return a.tx.Clear()
}

func (a jobBelongsToOutputFileTx) Count() int64 {
	return a.tx.Count()
}

func (a jobBelongsToOutputFileTx) Unscoped() *jobBelongsToOutputFileTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type jobDo struct{ gen.DO }

type IJobDo interface {
	gen.SubQuery
	Debug() IJobDo
	WithContext(ctx context.Context) IJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobDo
	WriteDB() IJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobDo
	Not(conds ...gen.Condition) IJobDo
	Or(conds ...gen.Condition) IJobDo
	Select(conds ...field.Expr) IJobDo
	Where(conds ...gen.Condition) IJobDo
	Order(conds ...field.Expr) IJobDo
	Distinct(cols ...field.Expr) IJobDo
	Omit(cols ...field.Expr) IJobDo
	Join(table schema.Tabler, on ...field.Expr) IJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobDo
	Group(cols ...field.Expr) IJobDo
	Having(conds ...gen.Condition) IJobDo
	Limit(limit int) IJobDo
	Offset(offset int) IJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobDo
	Unscoped() IJobDo
	Create(values ...*models.Job) error
	CreateInBatches(values []*models.Job, batchSize int) error
	Save(values ...*models.Job) error
	First() (*models.Job, error)
	Take() (*models.Job, error)
	Last() (*models.Job, error)
	Find() ([]*models.Job, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Job, err error)
	FindInBatches(result *[]*models.Job, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Job) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobDo
	Assign(attrs ...field.AssignExpr) IJobDo
	Joins(fields ...field.RelationField) IJobDo
	Preload(fields ...field.RelationField) IJobDo
	FirstOrInit() (*models.Job, error)
	FirstOrCreate() (*models.Job, error)
	FindByPage(offset int, limit int) (result []*models.Job, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobDo) Debug() IJobDo {
	return j.withDO(j.DO.Debug())
}

func (j jobDo) WithContext(ctx context.Context) IJobDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobDo) ReadDB() IJobDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobDo) WriteDB() IJobDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobDo) Session(config *gorm.Session) IJobDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobDo) Clauses(conds ...clause.Expression) IJobDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobDo) Returning(value interface{}, columns ...string) IJobDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobDo) Not(conds ...gen.Condition) IJobDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobDo) Or(conds ...gen.Condition) IJobDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobDo) Select(conds ...field.Expr) IJobDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobDo) Where(conds ...gen.Condition) IJobDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobDo) Order(conds ...field.Expr) IJobDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobDo) Distinct(cols ...field.Expr) IJobDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobDo) Omit(cols ...field.Expr) IJobDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobDo) Join(table schema.Tabler, on ...field.Expr) IJobDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobDo) Group(cols ...field.Expr) IJobDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobDo) Having(conds ...gen.Condition) IJobDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobDo) Limit(limit int) IJobDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobDo) Offset(offset int) IJobDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobDo) Unscoped() IJobDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobDo) Create(values ...*models.Job) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobDo) CreateInBatches(values []*models.Job, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobDo) Save(values ...*models.Job) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobDo) First() (*models.Job, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Job), nil
	}
}

func (j jobDo) Take() (*models.Job, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Job), nil
	}
}

func (j jobDo) Last() (*models.Job, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Job), nil
	}
}

func (j jobDo) Find() ([]*models.Job, error) {
	result, err := j.DO.Find()
	return result.([]*models.Job), err
}

func (j jobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Job, err error) {
	buf := make([]*models.Job, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobDo) FindInBatches(result *[]*models.Job, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobDo) Attrs(attrs ...field.AssignExpr) IJobDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobDo) Assign(attrs ...field.AssignExpr) IJobDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobDo) Joins(fields ...field.RelationField) IJobDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobDo) Preload(fields ...field.RelationField) IJobDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobDo) FirstOrInit() (*models.Job, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Job), nil
	}
}

func (j jobDo) FirstOrCreate() (*models.Job, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Job), nil
	}
}

func (j jobDo) FindByPage(offset int, limit int) (result []*models.Job, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobDo) Delete(models ...*models.Job) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobDo) withDO(do gen.Dao) *jobDo {
	j.DO = *do.(*gen.DO)
	return j
}
