// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"transcoder/server/internal/models"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&models.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.ID = field.NewField(tableName, "id")
	_user.CreatedAt = field.NewTime(tableName, "created_at")
	_user.UpdatedAt = field.NewTime(tableName, "updated_at")
	_user.Username = field.NewString(tableName, "username")
	_user.Email = field.NewString(tableName, "email")
	_user.PasswordHash = field.NewString(tableName, "password_hash")
	_user.Jobs = userHasManyJobs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Jobs", "models.Job"),
		Owner: struct {
			field.RelationField
			Jobs struct {
				field.RelationField
			}
			Tasks struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}
			Workflows struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Jobs.Owner", "models.User"),
			Jobs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Jobs.Owner.Jobs", "models.Job"),
			},
			Tasks: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Jobs.Owner.Tasks", "models.Task"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Tasks.Owner", "models.User"),
				},
				Workflow: struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow", "models.Workflow"),
					Owner: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow.Owner", "models.User"),
					},
					Jobs: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow.Jobs", "models.Job"),
					},
					Tasks: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow.Tasks", "models.Task"),
					},
				},
				Jobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Tasks.Jobs", "models.Job"),
				},
			},
			Workflows: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Jobs.Owner.Workflows", "models.Workflow"),
			},
			Files: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Jobs.Owner.Files", "models.File"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Files.Owner", "models.User"),
				},
				InputToJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Files.InputToJobs", "models.Job"),
				},
				OutputFromJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Files.OutputFromJobs", "models.Job"),
				},
			},
		},
		Task: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.Task", "models.Task"),
		},
		Workflow: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.Workflow", "models.Workflow"),
		},
		InputFile: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.InputFile", "models.File"),
		},
		OutputFile: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.OutputFile", "models.File"),
		},
	}

	_user.Tasks = userHasManyTasks{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tasks", "models.Task"),
	}

	_user.Workflows = userHasManyWorkflows{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Workflows", "models.Workflow"),
	}

	_user.Files = userHasManyFiles{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Files", "models.File"),
	}

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo

	ALL          field.Asterisk
	ID           field.Field
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Username     field.String
	Email        field.String
	PasswordHash field.String
	Jobs         userHasManyJobs

	Tasks userHasManyTasks

	Workflows userHasManyWorkflows

	Files userHasManyFiles

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.Username = field.NewString(table, "username")
	u.Email = field.NewString(table, "email")
	u.PasswordHash = field.NewString(table, "password_hash")

	u.fillFieldMap()

	return u
}

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["username"] = u.Username
	u.fieldMap["email"] = u.Email
	u.fieldMap["password_hash"] = u.PasswordHash

}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	u.Jobs.db = db.Session(&gorm.Session{Initialized: true})
	u.Jobs.db.Statement.ConnPool = db.Statement.ConnPool
	u.Tasks.db = db.Session(&gorm.Session{Initialized: true})
	u.Tasks.db.Statement.ConnPool = db.Statement.ConnPool
	u.Workflows.db = db.Session(&gorm.Session{Initialized: true})
	u.Workflows.db.Statement.ConnPool = db.Statement.ConnPool
	u.Files.db = db.Session(&gorm.Session{Initialized: true})
	u.Files.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	u.Jobs.db = db.Session(&gorm.Session{})
	u.Tasks.db = db.Session(&gorm.Session{})
	u.Workflows.db = db.Session(&gorm.Session{})
	u.Files.db = db.Session(&gorm.Session{})
	return u
}

type userHasManyJobs struct {
	db *gorm.DB

	field.RelationField

	Owner struct {
		field.RelationField
		Jobs struct {
			field.RelationField
		}
		Tasks struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Workflow struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Jobs struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
			}
			Jobs struct {
				field.RelationField
			}
		}
		Workflows struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			InputToJobs struct {
				field.RelationField
			}
			OutputFromJobs struct {
				field.RelationField
			}
		}
	}
	Task struct {
		field.RelationField
	}
	Workflow struct {
		field.RelationField
	}
	InputFile struct {
		field.RelationField
	}
	OutputFile struct {
		field.RelationField
	}
}

func (a userHasManyJobs) Where(conds ...field.Expr) *userHasManyJobs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyJobs) WithContext(ctx context.Context) *userHasManyJobs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyJobs) Session(session *gorm.Session) *userHasManyJobs {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyJobs) Model(m *models.User) *userHasManyJobsTx {
	return &userHasManyJobsTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyJobs) Unscoped() *userHasManyJobs {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyJobsTx struct{ tx *gorm.Association }

func (a userHasManyJobsTx) Find() (result []*models.Job, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyJobsTx) Append(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyJobsTx) Replace(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyJobsTx) Delete(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyJobsTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyJobsTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyJobsTx) Unscoped() *userHasManyJobsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManyTasks struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyTasks) Where(conds ...field.Expr) *userHasManyTasks {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyTasks) WithContext(ctx context.Context) *userHasManyTasks {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyTasks) Session(session *gorm.Session) *userHasManyTasks {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyTasks) Model(m *models.User) *userHasManyTasksTx {
	return &userHasManyTasksTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyTasks) Unscoped() *userHasManyTasks {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyTasksTx struct{ tx *gorm.Association }

func (a userHasManyTasksTx) Find() (result []*models.Task, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyTasksTx) Append(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyTasksTx) Replace(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyTasksTx) Delete(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyTasksTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyTasksTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyTasksTx) Unscoped() *userHasManyTasksTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManyWorkflows struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyWorkflows) Where(conds ...field.Expr) *userHasManyWorkflows {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyWorkflows) WithContext(ctx context.Context) *userHasManyWorkflows {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyWorkflows) Session(session *gorm.Session) *userHasManyWorkflows {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyWorkflows) Model(m *models.User) *userHasManyWorkflowsTx {
	return &userHasManyWorkflowsTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyWorkflows) Unscoped() *userHasManyWorkflows {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyWorkflowsTx struct{ tx *gorm.Association }

func (a userHasManyWorkflowsTx) Find() (result []*models.Workflow, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyWorkflowsTx) Append(values ...*models.Workflow) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyWorkflowsTx) Replace(values ...*models.Workflow) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyWorkflowsTx) Delete(values ...*models.Workflow) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyWorkflowsTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyWorkflowsTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyWorkflowsTx) Unscoped() *userHasManyWorkflowsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userHasManyFiles struct {
	db *gorm.DB

	field.RelationField
}

func (a userHasManyFiles) Where(conds ...field.Expr) *userHasManyFiles {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userHasManyFiles) WithContext(ctx context.Context) *userHasManyFiles {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userHasManyFiles) Session(session *gorm.Session) *userHasManyFiles {
	a.db = a.db.Session(session)
	return &a
}

func (a userHasManyFiles) Model(m *models.User) *userHasManyFilesTx {
	return &userHasManyFilesTx{a.db.Model(m).Association(a.Name())}
}

func (a userHasManyFiles) Unscoped() *userHasManyFiles {
	a.db = a.db.Unscoped()
	return &a
}

type userHasManyFilesTx struct{ tx *gorm.Association }

func (a userHasManyFilesTx) Find() (result []*models.File, err error) {
	return result, a.tx.Find(&result)
}

func (a userHasManyFilesTx) Append(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userHasManyFilesTx) Replace(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userHasManyFilesTx) Delete(values ...*models.File) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userHasManyFilesTx) Clear() error {
	return a.tx.Clear()
}

func (a userHasManyFilesTx) Count() int64 {
	return a.tx.Count()
}

func (a userHasManyFilesTx) Unscoped() *userHasManyFilesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userDo struct{ gen.DO }

type IUserDo interface {
	gen.SubQuery
	Debug() IUserDo
	WithContext(ctx context.Context) IUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDo
	WriteDB() IUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDo
	Not(conds ...gen.Condition) IUserDo
	Or(conds ...gen.Condition) IUserDo
	Select(conds ...field.Expr) IUserDo
	Where(conds ...gen.Condition) IUserDo
	Order(conds ...field.Expr) IUserDo
	Distinct(cols ...field.Expr) IUserDo
	Omit(cols ...field.Expr) IUserDo
	Join(table schema.Tabler, on ...field.Expr) IUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDo
	Group(cols ...field.Expr) IUserDo
	Having(conds ...gen.Condition) IUserDo
	Limit(limit int) IUserDo
	Offset(offset int) IUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo
	Unscoped() IUserDo
	Create(values ...*models.User) error
	CreateInBatches(values []*models.User, batchSize int) error
	Save(values ...*models.User) error
	First() (*models.User, error)
	Take() (*models.User, error)
	Last() (*models.User, error)
	Find() ([]*models.User, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.User, err error)
	FindInBatches(result *[]*models.User, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.User) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDo
	Assign(attrs ...field.AssignExpr) IUserDo
	Joins(fields ...field.RelationField) IUserDo
	Preload(fields ...field.RelationField) IUserDo
	FirstOrInit() (*models.User, error)
	FirstOrCreate() (*models.User, error)
	FindByPage(offset int, limit int) (result []*models.User, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userDo) Debug() IUserDo {
	return u.withDO(u.DO.Debug())
}

func (u userDo) WithContext(ctx context.Context) IUserDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDo) ReadDB() IUserDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDo) WriteDB() IUserDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDo) Session(config *gorm.Session) IUserDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDo) Clauses(conds ...clause.Expression) IUserDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDo) Returning(value interface{}, columns ...string) IUserDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDo) Not(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDo) Or(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDo) Select(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDo) Where(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDo) Order(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDo) Distinct(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDo) Omit(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDo) Join(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDo) Group(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDo) Having(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDo) Limit(limit int) IUserDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDo) Offset(offset int) IUserDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDo) Unscoped() IUserDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDo) Create(values ...*models.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDo) CreateInBatches(values []*models.User, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDo) Save(values ...*models.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDo) First() (*models.User, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) Take() (*models.User, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) Last() (*models.User, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) Find() ([]*models.User, error) {
	result, err := u.DO.Find()
	return result.([]*models.User), err
}

func (u userDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.User, err error) {
	buf := make([]*models.User, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDo) FindInBatches(result *[]*models.User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDo) Attrs(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDo) Assign(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDo) Joins(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDo) Preload(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDo) FirstOrInit() (*models.User, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) FirstOrCreate() (*models.User, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.User), nil
	}
}

func (u userDo) FindByPage(offset int, limit int) (result []*models.User, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDo) Delete(models ...*models.User) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDo) withDO(do gen.Dao) *userDo {
	u.DO = *do.(*gen.DO)
	return u
}
