// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"transcoder/server/internal/models"
)

func newWorkflow(db *gorm.DB, opts ...gen.DOOption) workflow {
	_workflow := workflow{}

	_workflow.workflowDo.UseDB(db, opts...)
	_workflow.workflowDo.UseModel(&models.Workflow{})

	tableName := _workflow.workflowDo.TableName()
	_workflow.ALL = field.NewAsterisk(tableName)
	_workflow.ID = field.NewField(tableName, "id")
	_workflow.CreatedAt = field.NewTime(tableName, "created_at")
	_workflow.UpdatedAt = field.NewTime(tableName, "updated_at")
	_workflow.Name = field.NewString(tableName, "name")
	_workflow.TargetFormat = field.NewString(tableName, "target_format")
	_workflow.Params = field.NewString(tableName, "params")
	_workflow.OwnerID = field.NewField(tableName, "owner_id")
	_workflow.Jobs = workflowHasManyJobs{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Jobs", "models.Job"),
		Owner: struct {
			field.RelationField
			Jobs struct {
				field.RelationField
			}
			Tasks struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}
			Workflows struct {
				field.RelationField
			}
			Files struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Jobs.Owner", "models.User"),
			Jobs: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Jobs.Owner.Jobs", "models.Job"),
			},
			Tasks: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Workflow struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}
				Jobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Jobs.Owner.Tasks", "models.Task"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Tasks.Owner", "models.User"),
				},
				Workflow: struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					Jobs struct {
						field.RelationField
					}
					Tasks struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow", "models.Workflow"),
					Owner: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow.Owner", "models.User"),
					},
					Jobs: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow.Jobs", "models.Job"),
					},
					Tasks: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Jobs.Owner.Tasks.Workflow.Tasks", "models.Task"),
					},
				},
				Jobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Tasks.Jobs", "models.Job"),
				},
			},
			Workflows: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Jobs.Owner.Workflows", "models.Workflow"),
			},
			Files: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				InputToJobs struct {
					field.RelationField
				}
				OutputFromJobs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Jobs.Owner.Files", "models.File"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Files.Owner", "models.User"),
				},
				InputToJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Files.InputToJobs", "models.Job"),
				},
				OutputFromJobs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Jobs.Owner.Files.OutputFromJobs", "models.Job"),
				},
			},
		},
		Task: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.Task", "models.Task"),
		},
		Workflow: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.Workflow", "models.Workflow"),
		},
		InputFile: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.InputFile", "models.File"),
		},
		OutputFile: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Jobs.OutputFile", "models.File"),
		},
	}

	_workflow.Tasks = workflowHasManyTasks{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Tasks", "models.Task"),
	}

	_workflow.Owner = workflowBelongsToOwner{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Owner", "models.User"),
	}

	_workflow.fillFieldMap()

	return _workflow
}

type workflow struct {
	workflowDo

	ALL          field.Asterisk
	ID           field.Field
	CreatedAt    field.Time
	UpdatedAt    field.Time
	Name         field.String
	TargetFormat field.String
	Params       field.String
	OwnerID      field.Field
	Jobs         workflowHasManyJobs

	Tasks workflowHasManyTasks

	Owner workflowBelongsToOwner

	fieldMap map[string]field.Expr
}

func (w workflow) Table(newTableName string) *workflow {
	w.workflowDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workflow) As(alias string) *workflow {
	w.workflowDo.DO = *(w.workflowDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workflow) updateTableName(table string) *workflow {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewField(table, "id")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")
	w.Name = field.NewString(table, "name")
	w.TargetFormat = field.NewString(table, "target_format")
	w.Params = field.NewString(table, "params")
	w.OwnerID = field.NewField(table, "owner_id")

	w.fillFieldMap()

	return w
}

func (w *workflow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workflow) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 10)
	w.fieldMap["id"] = w.ID
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
	w.fieldMap["name"] = w.Name
	w.fieldMap["target_format"] = w.TargetFormat
	w.fieldMap["params"] = w.Params
	w.fieldMap["owner_id"] = w.OwnerID

}

func (w workflow) clone(db *gorm.DB) workflow {
	w.workflowDo.ReplaceConnPool(db.Statement.ConnPool)
	w.Jobs.db = db.Session(&gorm.Session{Initialized: true})
	w.Jobs.db.Statement.ConnPool = db.Statement.ConnPool
	w.Tasks.db = db.Session(&gorm.Session{Initialized: true})
	w.Tasks.db.Statement.ConnPool = db.Statement.ConnPool
	w.Owner.db = db.Session(&gorm.Session{Initialized: true})
	w.Owner.db.Statement.ConnPool = db.Statement.ConnPool
	return w
}

func (w workflow) replaceDB(db *gorm.DB) workflow {
	w.workflowDo.ReplaceDB(db)
	w.Jobs.db = db.Session(&gorm.Session{})
	w.Tasks.db = db.Session(&gorm.Session{})
	w.Owner.db = db.Session(&gorm.Session{})
	return w
}

type workflowHasManyJobs struct {
	db *gorm.DB

	field.RelationField

	Owner struct {
		field.RelationField
		Jobs struct {
			field.RelationField
		}
		Tasks struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Workflow struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Jobs struct {
					field.RelationField
				}
				Tasks struct {
					field.RelationField
				}
			}
			Jobs struct {
				field.RelationField
			}
		}
		Workflows struct {
			field.RelationField
		}
		Files struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			InputToJobs struct {
				field.RelationField
			}
			OutputFromJobs struct {
				field.RelationField
			}
		}
	}
	Task struct {
		field.RelationField
	}
	Workflow struct {
		field.RelationField
	}
	InputFile struct {
		field.RelationField
	}
	OutputFile struct {
		field.RelationField
	}
}

func (a workflowHasManyJobs) Where(conds ...field.Expr) *workflowHasManyJobs {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workflowHasManyJobs) WithContext(ctx context.Context) *workflowHasManyJobs {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workflowHasManyJobs) Session(session *gorm.Session) *workflowHasManyJobs {
	a.db = a.db.Session(session)
	return &a
}

func (a workflowHasManyJobs) Model(m *models.Workflow) *workflowHasManyJobsTx {
	return &workflowHasManyJobsTx{a.db.Model(m).Association(a.Name())}
}

func (a workflowHasManyJobs) Unscoped() *workflowHasManyJobs {
	a.db = a.db.Unscoped()
	return &a
}

type workflowHasManyJobsTx struct{ tx *gorm.Association }

func (a workflowHasManyJobsTx) Find() (result []*models.Job, err error) {
	return result, a.tx.Find(&result)
}

func (a workflowHasManyJobsTx) Append(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workflowHasManyJobsTx) Replace(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workflowHasManyJobsTx) Delete(values ...*models.Job) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workflowHasManyJobsTx) Clear() error {
	return a.tx.Clear()
}

func (a workflowHasManyJobsTx) Count() int64 {
	return a.tx.Count()
}

func (a workflowHasManyJobsTx) Unscoped() *workflowHasManyJobsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workflowHasManyTasks struct {
	db *gorm.DB

	field.RelationField
}

func (a workflowHasManyTasks) Where(conds ...field.Expr) *workflowHasManyTasks {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workflowHasManyTasks) WithContext(ctx context.Context) *workflowHasManyTasks {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workflowHasManyTasks) Session(session *gorm.Session) *workflowHasManyTasks {
	a.db = a.db.Session(session)
	return &a
}

func (a workflowHasManyTasks) Model(m *models.Workflow) *workflowHasManyTasksTx {
	return &workflowHasManyTasksTx{a.db.Model(m).Association(a.Name())}
}

func (a workflowHasManyTasks) Unscoped() *workflowHasManyTasks {
	a.db = a.db.Unscoped()
	return &a
}

type workflowHasManyTasksTx struct{ tx *gorm.Association }

func (a workflowHasManyTasksTx) Find() (result []*models.Task, err error) {
	return result, a.tx.Find(&result)
}

func (a workflowHasManyTasksTx) Append(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workflowHasManyTasksTx) Replace(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workflowHasManyTasksTx) Delete(values ...*models.Task) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workflowHasManyTasksTx) Clear() error {
	return a.tx.Clear()
}

func (a workflowHasManyTasksTx) Count() int64 {
	return a.tx.Count()
}

func (a workflowHasManyTasksTx) Unscoped() *workflowHasManyTasksTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workflowBelongsToOwner struct {
	db *gorm.DB

	field.RelationField
}

func (a workflowBelongsToOwner) Where(conds ...field.Expr) *workflowBelongsToOwner {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a workflowBelongsToOwner) WithContext(ctx context.Context) *workflowBelongsToOwner {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a workflowBelongsToOwner) Session(session *gorm.Session) *workflowBelongsToOwner {
	a.db = a.db.Session(session)
	return &a
}

func (a workflowBelongsToOwner) Model(m *models.Workflow) *workflowBelongsToOwnerTx {
	return &workflowBelongsToOwnerTx{a.db.Model(m).Association(a.Name())}
}

func (a workflowBelongsToOwner) Unscoped() *workflowBelongsToOwner {
	a.db = a.db.Unscoped()
	return &a
}

type workflowBelongsToOwnerTx struct{ tx *gorm.Association }

func (a workflowBelongsToOwnerTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a workflowBelongsToOwnerTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a workflowBelongsToOwnerTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a workflowBelongsToOwnerTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a workflowBelongsToOwnerTx) Clear() error {
	return a.tx.Clear()
}

func (a workflowBelongsToOwnerTx) Count() int64 {
	return a.tx.Count()
}

func (a workflowBelongsToOwnerTx) Unscoped() *workflowBelongsToOwnerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type workflowDo struct{ gen.DO }

type IWorkflowDo interface {
	gen.SubQuery
	Debug() IWorkflowDo
	WithContext(ctx context.Context) IWorkflowDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWorkflowDo
	WriteDB() IWorkflowDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWorkflowDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWorkflowDo
	Not(conds ...gen.Condition) IWorkflowDo
	Or(conds ...gen.Condition) IWorkflowDo
	Select(conds ...field.Expr) IWorkflowDo
	Where(conds ...gen.Condition) IWorkflowDo
	Order(conds ...field.Expr) IWorkflowDo
	Distinct(cols ...field.Expr) IWorkflowDo
	Omit(cols ...field.Expr) IWorkflowDo
	Join(table schema.Tabler, on ...field.Expr) IWorkflowDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWorkflowDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWorkflowDo
	Group(cols ...field.Expr) IWorkflowDo
	Having(conds ...gen.Condition) IWorkflowDo
	Limit(limit int) IWorkflowDo
	Offset(offset int) IWorkflowDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkflowDo
	Unscoped() IWorkflowDo
	Create(values ...*models.Workflow) error
	CreateInBatches(values []*models.Workflow, batchSize int) error
	Save(values ...*models.Workflow) error
	First() (*models.Workflow, error)
	Take() (*models.Workflow, error)
	Last() (*models.Workflow, error)
	Find() ([]*models.Workflow, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Workflow, err error)
	FindInBatches(result *[]*models.Workflow, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Workflow) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWorkflowDo
	Assign(attrs ...field.AssignExpr) IWorkflowDo
	Joins(fields ...field.RelationField) IWorkflowDo
	Preload(fields ...field.RelationField) IWorkflowDo
	FirstOrInit() (*models.Workflow, error)
	FirstOrCreate() (*models.Workflow, error)
	FindByPage(offset int, limit int) (result []*models.Workflow, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWorkflowDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w workflowDo) Debug() IWorkflowDo {
	return w.withDO(w.DO.Debug())
}

func (w workflowDo) WithContext(ctx context.Context) IWorkflowDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workflowDo) ReadDB() IWorkflowDo {
	return w.Clauses(dbresolver.Read)
}

func (w workflowDo) WriteDB() IWorkflowDo {
	return w.Clauses(dbresolver.Write)
}

func (w workflowDo) Session(config *gorm.Session) IWorkflowDo {
	return w.withDO(w.DO.Session(config))
}

func (w workflowDo) Clauses(conds ...clause.Expression) IWorkflowDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workflowDo) Returning(value interface{}, columns ...string) IWorkflowDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workflowDo) Not(conds ...gen.Condition) IWorkflowDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workflowDo) Or(conds ...gen.Condition) IWorkflowDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workflowDo) Select(conds ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workflowDo) Where(conds ...gen.Condition) IWorkflowDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workflowDo) Order(conds ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workflowDo) Distinct(cols ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workflowDo) Omit(cols ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workflowDo) Join(table schema.Tabler, on ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workflowDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workflowDo) RightJoin(table schema.Tabler, on ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workflowDo) Group(cols ...field.Expr) IWorkflowDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workflowDo) Having(conds ...gen.Condition) IWorkflowDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workflowDo) Limit(limit int) IWorkflowDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workflowDo) Offset(offset int) IWorkflowDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workflowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWorkflowDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workflowDo) Unscoped() IWorkflowDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workflowDo) Create(values ...*models.Workflow) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workflowDo) CreateInBatches(values []*models.Workflow, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workflowDo) Save(values ...*models.Workflow) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workflowDo) First() (*models.Workflow, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Workflow), nil
	}
}

func (w workflowDo) Take() (*models.Workflow, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Workflow), nil
	}
}

func (w workflowDo) Last() (*models.Workflow, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Workflow), nil
	}
}

func (w workflowDo) Find() ([]*models.Workflow, error) {
	result, err := w.DO.Find()
	return result.([]*models.Workflow), err
}

func (w workflowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Workflow, err error) {
	buf := make([]*models.Workflow, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workflowDo) FindInBatches(result *[]*models.Workflow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workflowDo) Attrs(attrs ...field.AssignExpr) IWorkflowDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workflowDo) Assign(attrs ...field.AssignExpr) IWorkflowDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workflowDo) Joins(fields ...field.RelationField) IWorkflowDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workflowDo) Preload(fields ...field.RelationField) IWorkflowDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workflowDo) FirstOrInit() (*models.Workflow, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Workflow), nil
	}
}

func (w workflowDo) FirstOrCreate() (*models.Workflow, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Workflow), nil
	}
}

func (w workflowDo) FindByPage(offset int, limit int) (result []*models.Workflow, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workflowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workflowDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workflowDo) Delete(models ...*models.Workflow) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workflowDo) withDO(do gen.Dao) *workflowDo {
	w.DO = *do.(*gen.DO)
	return w
}
