[package]
name = "compute-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
compute-types.workspace = true
compute-engine.workspace = true
compute-server-adapter.workspace = true
anyhow.workspace = true
tokio.workspace = true
redis.workspace = true
chrono.workspace = true
uuid.workspace = true
serde = { workspace = true, features = ["derive"] }
config.workspace = true
validator.workspace = true
dotenvy = "0.15.7"
serde_json = "1.0.149"
aws-config = { workspace = true, features = ["rustls", "behavior-version-latest"] }
aws-sdk-s3 = { workspace = true, features = ["rustls"] }
tempfile.workspace = true
rustls.workspace = true
image.workspace = true



